import time
from typing import List, Dict, Optional

from repository import Repository


class ChatRepository(Repository):
    """Manages chat history state and persistence for a specific user-character pair."""

    def __init__(self, data_dir: str, user: str, character: str) -> None:
        super().__init__(
            data_dir,
            f"{self.encode_filename_part(user)}_{self.encode_filename_part(character)}.json",
        )
        self.user = user
        self.character = character

    def get_chat_history(self) -> List[Dict[str, str]]:
        """Returns the current chat history.

        Returns:
            The list of message dictionaries representing the chat history.
        """
        return self.data

    def add_assistant_message(self, content: str, tool_calls: Optional[List] = None) -> None:
        """Appends an assistant message to the chat history.

        Args:
            content: The text content of the message.
            tool_calls: Optional list of tool call data adhering to LLM specifications.
        """
        history = self.data
        now = int(1000 * time.time())
        msg = {"timestamp": now, "role": "assistant", "content": content}

        if tool_calls:
            msg["tool_calls"] = tool_calls

        history.append(msg)
        self.data = history
        self.save_changes()

    def add_user_message(self, content: str) -> None:
        """Appends a user message to the chat history.

        Args:
            content: The text content of the user message.
        """
        self._add_chat_entry("user", content)

    def add_tool_message(self, content: str, func_name: str, tool_call_id: str) -> None:
        """Appends a tool execution result to the chat history.

        Args:
            content: The output or error message from the tool execution.
            func_name: The name of the executed function.
            tool_call_id: Unique identifier for the corresponding tool call.
        """
        self._add_chat_entry("tool", content, func_name, tool_call_id)

    def add_agent_message(self, content: str) -> None:
        """Appends an agent message to the chat history.

        Args:
            content: The text content generated by the agent.
        """
        self._add_chat_entry("user", content)

    def add_raw_message(self, content: Dict) -> None:
        """Appends a raw message dictionary directly to the history.

        Args:
            content: A pre-formatted dictionary representing the message.
        """
        self.data.append(content)
        self.save_changes()

    def _add_chat_entry(
        self, role: str, content: str, func_name: str = "", tool_call_id: str = ""
    ) -> None:
        """Internal helper to format and append chat entries.

        Args:
            role: The message role (e.g., 'user', 'assistant', 'tool').
            content: The message content or result string.
            func_name: Function name for tool messages.
            tool_call_id: Tool call identifier for tool messages.
        """
        history = self.data if role != "system" else []

        now = int(1000 * time.time())
        if role == "tool":
            history.append({
                "timestamp": now,
                "role": "tool",
                "name": func_name,
                "content": content,
                "tool_call_id": tool_call_id,
            })
        elif role == "agent":
            history.append({"timestamp": now, "role": "user", "content": content, "is_agent": True})
        else:
            history.append({"timestamp": now, "role": role, "content": content, "is_agent": False})

        self.data = history
        self.save_changes()

    def delete_message(self, timestamp: int) -> bool:
        """Deletes a message block starting from the given timestamp.

        Args:
            timestamp: The target message timestamp to locate and remove.

        Returns:
            True if messages were deleted, False otherwise.
        """
        target_idx = -1

        for i, msg in enumerate(self.data):
            if msg.get("timestamp") == timestamp:
                target_idx = i
                break

        if target_idx == -1:
            return False

        # Identify the upper bound of the block to remove.
        # The block extends until the next user message or end of history.
        delete_end_idx = target_idx + 1
        while delete_end_idx < len(self.data) and self.data[delete_end_idx].get("role") != "user":
            delete_end_idx += 1

        initial_len = len(self.data)
        del self.data[target_idx:delete_end_idx]

        if len(self.data) < initial_len:
            self.save_changes()
            return True

        return False

    def delete_last_assistant_message(self) -> bool:
        """Removes the most recent assistant response and its associated tool calls.

        Returns:
            True if messages were deleted, False otherwise.
        """
        if not self.data:
            return False

        last_user_idx = -1
        for i in range(len(self.data) - 1, -1, -1):
            if self.data[i].get("role") == "user":
                last_user_idx = i
                break

        # If the last message is already a user message, nothing to delete.
        if last_user_idx == len(self.data) - 1:
            return False

        initial_len = len(self.data)
        self.data = self.data[: last_user_idx + 1]

        if len(self.data) < initial_len:
            self.save_changes()
            return True

        return False